/* tslint:disable */
/* eslint-disable */
/**
 * Nager.Date API Reference
 * The Nager.Date API is a free public service that provides reliable information about public holidays and long weekends for countries around the world. It allows developers to query national holiday dates, check whether a specific day is a public holiday, list upcoming holidays, and explore long-weekend data.    By using the API, you agree to the <a href=\"https://date.nager.at/Legal/TermsOfService\">Terms of Service.</a>
 *
 * The version of the OpenAPI document: v3
 * Contact: hello@nager.software
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type {
  CountryInfoWithBordersDto,
  CountryV3Dto,
  ProblemDetails,
} from "../models/index";
import {
  CountryInfoWithBordersDtoFromJSON,
  CountryInfoWithBordersDtoToJSON,
  CountryV3DtoFromJSON,
  CountryV3DtoToJSON,
  ProblemDetailsFromJSON,
  ProblemDetailsToJSON,
} from "../models/index";

export interface ApiV3CountryInfoCountryCodeGetRequest {
  countryCode: string;
}

/**
 *
 */
export class CountryApi extends runtime.BaseAPI {
  /**
   * This endpoint returns all countries for which public-holiday data is available. Each entry includes the country\'s name and ISO code.
   * Retrieve the complete list of all countries supported by the Nager.Date API
   */
  async apiV3AvailableCountriesGetRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<CountryV3Dto>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/v3/AvailableCountries`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(CountryV3DtoFromJSON),
    );
  }

  /**
   * This endpoint returns all countries for which public-holiday data is available. Each entry includes the country\'s name and ISO code.
   * Retrieve the complete list of all countries supported by the Nager.Date API
   */
  async apiV3AvailableCountriesGet(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<CountryV3Dto>> {
    const response = await this.apiV3AvailableCountriesGetRaw(initOverrides);
    return await response.value();
  }

  /**
   * Provide a valid `ISO 3166-1 alpha-2` country code to retrieve country metadata. The response includes commonly used and official country names, the assigned region, and if available neighboring countries based on geographical borders.
   * Retrieves detailed information about a specific country
   */
  async apiV3CountryInfoCountryCodeGetRaw(
    requestParameters: ApiV3CountryInfoCountryCodeGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CountryInfoWithBordersDto>> {
    if (requestParameters["countryCode"] == null) {
      throw new runtime.RequiredError(
        "countryCode",
        'Required parameter "countryCode" was null or undefined when calling apiV3CountryInfoCountryCodeGet().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/v3/CountryInfo/{countryCode}`;
    urlPath = urlPath.replace(
      `{${"countryCode"}}`,
      encodeURIComponent(String(requestParameters["countryCode"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      CountryInfoWithBordersDtoFromJSON(jsonValue),
    );
  }

  /**
   * Provide a valid `ISO 3166-1 alpha-2` country code to retrieve country metadata. The response includes commonly used and official country names, the assigned region, and if available neighboring countries based on geographical borders.
   * Retrieves detailed information about a specific country
   */
  async apiV3CountryInfoCountryCodeGet(
    requestParameters: ApiV3CountryInfoCountryCodeGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CountryInfoWithBordersDto> {
    const response = await this.apiV3CountryInfoCountryCodeGetRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }
}
