/* tslint:disable */
/* eslint-disable */
/**
 * Nager.Date API Reference
 * The Nager.Date API is a free public service that provides reliable information about public holidays and long weekends for countries around the world. It allows developers to query national holiday dates, check whether a specific day is a public holiday, list upcoming holidays, and explore long-weekend data.    By using the API, you agree to the <a href=\"https://date.nager.at/Legal/TermsOfService\">Terms of Service.</a>
 *
 * The version of the OpenAPI document: v3
 * Contact: hello@nager.software
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { LongWeekendV3Dto, ProblemDetails } from "../models/index";
import {
  LongWeekendV3DtoFromJSON,
  LongWeekendV3DtoToJSON,
  ProblemDetailsFromJSON,
  ProblemDetailsToJSON,
} from "../models/index";

export interface ApiV3LongWeekendYearCountryCodeGetRequest {
  year: number;
  countryCode: string;
  availableBridgeDays?: number;
  subdivisionCode?: string;
}

/**
 *
 */
export class LongWeekendApi extends runtime.BaseAPI {
  /**
   * A long weekend is calculated based on public holidays that create an extended break of at least three consecutive days. Optional bridge days-weekdays between a holiday and a weekend-can be included to identify potential extended leave opportunities.
   * Retrieve all long weekends for a given country and year
   */
  async apiV3LongWeekendYearCountryCodeGetRaw(
    requestParameters: ApiV3LongWeekendYearCountryCodeGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<LongWeekendV3Dto>>> {
    if (requestParameters["year"] == null) {
      throw new runtime.RequiredError(
        "year",
        'Required parameter "year" was null or undefined when calling apiV3LongWeekendYearCountryCodeGet().',
      );
    }

    if (requestParameters["countryCode"] == null) {
      throw new runtime.RequiredError(
        "countryCode",
        'Required parameter "countryCode" was null or undefined when calling apiV3LongWeekendYearCountryCodeGet().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["availableBridgeDays"] != null) {
      queryParameters["availableBridgeDays"] =
        requestParameters["availableBridgeDays"];
    }

    if (requestParameters["subdivisionCode"] != null) {
      queryParameters["subdivisionCode"] = requestParameters["subdivisionCode"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/v3/LongWeekend/{year}/{countryCode}`;
    urlPath = urlPath.replace(
      `{${"year"}}`,
      encodeURIComponent(String(requestParameters["year"])),
    );
    urlPath = urlPath.replace(
      `{${"countryCode"}}`,
      encodeURIComponent(String(requestParameters["countryCode"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(LongWeekendV3DtoFromJSON),
    );
  }

  /**
   * A long weekend is calculated based on public holidays that create an extended break of at least three consecutive days. Optional bridge days-weekdays between a holiday and a weekend-can be included to identify potential extended leave opportunities.
   * Retrieve all long weekends for a given country and year
   */
  async apiV3LongWeekendYearCountryCodeGet(
    requestParameters: ApiV3LongWeekendYearCountryCodeGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<LongWeekendV3Dto>> {
    const response = await this.apiV3LongWeekendYearCountryCodeGetRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }
}
