/* tslint:disable */
/* eslint-disable */
/**
 * Nager.Date API Reference
 * The Nager.Date API is a free public service that provides reliable information about public holidays and long weekends for countries around the world. It allows developers to query national holiday dates, check whether a specific day is a public holiday, list upcoming holidays, and explore long-weekend data.    By using the API, you agree to the <a href=\"https://date.nager.at/Legal/TermsOfService\">Terms of Service.</a>
 *
 * The version of the OpenAPI document: v3
 * Contact: hello@nager.software
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { ProblemDetails, PublicHolidayV3Dto } from "../models/index";
import {
  ProblemDetailsFromJSON,
  ProblemDetailsToJSON,
  PublicHolidayV3DtoFromJSON,
  PublicHolidayV3DtoToJSON,
} from "../models/index";

export interface ApiV3IsTodayPublicHolidayCountryCodeGetRequest {
  countryCode: string;
  countyCode?: string;
  offset?: number;
}

export interface ApiV3NextPublicHolidaysCountryCodeGetRequest {
  countryCode: string;
}

export interface ApiV3PublicHolidaysYearCountryCodeGetRequest {
  year: number;
  countryCode: string;
}

/**
 *
 */
export class PublicHolidayApi extends runtime.BaseAPI {
  /**
   * By default, the calculation is based on the current UTC date. You may optionally provide a timezone offset to evaluate the holiday status relative to a different local timezone.  This endpoint is optimized for simple command-line or automation workflows where only the HTTP status code is required  ``` STATUSCODE=$(curl --silent --output /dev/stderr --write-out \"%{http_code}\" https://date.nager.at/Api/v3/IsTodayPublicHoliday/AT) if [ $STATUSCODE -ne 200 ]; then     # handle error fi ```
   * Determines whether today is a public holiday in the specified country, optionally adjusted by a UTC offset
   */
  async apiV3IsTodayPublicHolidayCountryCodeGetRaw(
    requestParameters: ApiV3IsTodayPublicHolidayCountryCodeGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["countryCode"] == null) {
      throw new runtime.RequiredError(
        "countryCode",
        'Required parameter "countryCode" was null or undefined when calling apiV3IsTodayPublicHolidayCountryCodeGet().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["countyCode"] != null) {
      queryParameters["countyCode"] = requestParameters["countyCode"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/v3/IsTodayPublicHoliday/{countryCode}`;
    urlPath = urlPath.replace(
      `{${"countryCode"}}`,
      encodeURIComponent(String(requestParameters["countryCode"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * By default, the calculation is based on the current UTC date. You may optionally provide a timezone offset to evaluate the holiday status relative to a different local timezone.  This endpoint is optimized for simple command-line or automation workflows where only the HTTP status code is required  ``` STATUSCODE=$(curl --silent --output /dev/stderr --write-out \"%{http_code}\" https://date.nager.at/Api/v3/IsTodayPublicHoliday/AT) if [ $STATUSCODE -ne 200 ]; then     # handle error fi ```
   * Determines whether today is a public holiday in the specified country, optionally adjusted by a UTC offset
   */
  async apiV3IsTodayPublicHolidayCountryCodeGet(
    requestParameters: ApiV3IsTodayPublicHolidayCountryCodeGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.apiV3IsTodayPublicHolidayCountryCodeGetRaw(
      requestParameters,
      initOverrides,
    );
  }

  /**
   * The list includes only future holidays relative to the current date and is useful for forecasting, event planning, and applications that provide forward-looking holiday insights.
   * Retrieve all upcoming public holidays occurring within the next 365 days for a given country
   */
  async apiV3NextPublicHolidaysCountryCodeGetRaw(
    requestParameters: ApiV3NextPublicHolidaysCountryCodeGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<PublicHolidayV3Dto>>> {
    if (requestParameters["countryCode"] == null) {
      throw new runtime.RequiredError(
        "countryCode",
        'Required parameter "countryCode" was null or undefined when calling apiV3NextPublicHolidaysCountryCodeGet().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/v3/NextPublicHolidays/{countryCode}`;
    urlPath = urlPath.replace(
      `{${"countryCode"}}`,
      encodeURIComponent(String(requestParameters["countryCode"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(PublicHolidayV3DtoFromJSON),
    );
  }

  /**
   * The list includes only future holidays relative to the current date and is useful for forecasting, event planning, and applications that provide forward-looking holiday insights.
   * Retrieve all upcoming public holidays occurring within the next 365 days for a given country
   */
  async apiV3NextPublicHolidaysCountryCodeGet(
    requestParameters: ApiV3NextPublicHolidaysCountryCodeGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<PublicHolidayV3Dto> | null | undefined> {
    const response = await this.apiV3NextPublicHolidaysCountryCodeGetRaw(
      requestParameters,
      initOverrides,
    );
    switch (response.raw.status) {
      case 200:
        return await response.value();
      case 204:
        return null;
      default:
        return await response.value();
    }
  }

  /**
   * This global endpoint aggregates upcoming holidays across all supported countries, enabling international systems to detect near-term events.
   * Retrieve all public holidays occurring worldwide within the next 7 days
   */
  async apiV3NextPublicHolidaysWorldwideGetRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<PublicHolidayV3Dto>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/v3/NextPublicHolidaysWorldwide`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(PublicHolidayV3DtoFromJSON),
    );
  }

  /**
   * This global endpoint aggregates upcoming holidays across all supported countries, enabling international systems to detect near-term events.
   * Retrieve all public holidays occurring worldwide within the next 7 days
   */
  async apiV3NextPublicHolidaysWorldwideGet(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<PublicHolidayV3Dto> | null | undefined> {
    const response =
      await this.apiV3NextPublicHolidaysWorldwideGetRaw(initOverrides);
    switch (response.raw.status) {
      case 200:
        return await response.value();
      case 204:
        return null;
      default:
        return await response.value();
    }
  }

  /**
   * This endpoint returns all officially recognized public holidays for the given country and year. Each holiday entry includes the local and English holiday names, information about whether the holiday applies nationally or only in specific subdivisions, and the associated holiday type classifications.
   * Retrieve the list of all public holidays for the specified year and country
   */
  async apiV3PublicHolidaysYearCountryCodeGetRaw(
    requestParameters: ApiV3PublicHolidaysYearCountryCodeGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<PublicHolidayV3Dto>>> {
    if (requestParameters["year"] == null) {
      throw new runtime.RequiredError(
        "year",
        'Required parameter "year" was null or undefined when calling apiV3PublicHolidaysYearCountryCodeGet().',
      );
    }

    if (requestParameters["countryCode"] == null) {
      throw new runtime.RequiredError(
        "countryCode",
        'Required parameter "countryCode" was null or undefined when calling apiV3PublicHolidaysYearCountryCodeGet().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/v3/PublicHolidays/{year}/{countryCode}`;
    urlPath = urlPath.replace(
      `{${"year"}}`,
      encodeURIComponent(String(requestParameters["year"])),
    );
    urlPath = urlPath.replace(
      `{${"countryCode"}}`,
      encodeURIComponent(String(requestParameters["countryCode"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(PublicHolidayV3DtoFromJSON),
    );
  }

  /**
   * This endpoint returns all officially recognized public holidays for the given country and year. Each holiday entry includes the local and English holiday names, information about whether the holiday applies nationally or only in specific subdivisions, and the associated holiday type classifications.
   * Retrieve the list of all public holidays for the specified year and country
   */
  async apiV3PublicHolidaysYearCountryCodeGet(
    requestParameters: ApiV3PublicHolidaysYearCountryCodeGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<PublicHolidayV3Dto>> {
    const response = await this.apiV3PublicHolidaysYearCountryCodeGetRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }
}
