/* tslint:disable */
/* eslint-disable */
/**
 * Nager.Date API Reference
 * The Nager.Date API is a free public service that provides reliable information about public holidays and long weekends for countries around the world. It allows developers to query national holiday dates, check whether a specific day is a public holiday, list upcoming holidays, and explore long-weekend data.    By using the API, you agree to the <a href=\"https://date.nager.at/Legal/TermsOfService\">Terms of Service.</a>
 *
 * The version of the OpenAPI document: v3
 * Contact: hello@nager.software
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { VersionInfoDto } from "../models/index";
import { VersionInfoDtoFromJSON, VersionInfoDtoToJSON } from "../models/index";

/**
 *
 */
export class VersionApi extends runtime.BaseAPI {
  /**
   * This endpoint returns detailed version information about the Nager.Date implementation running on the server, including the exact NuGet package version used by the API.
   * Retrieve the current version information of the Nager.Date library
   */
  async apiV3VersionGetRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<VersionInfoDto>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/v3/Version`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      VersionInfoDtoFromJSON(jsonValue),
    );
  }

  /**
   * This endpoint returns detailed version information about the Nager.Date implementation running on the server, including the exact NuGet package version used by the API.
   * Retrieve the current version information of the Nager.Date library
   */
  async apiV3VersionGet(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<VersionInfoDto> {
    const response = await this.apiV3VersionGetRaw(initOverrides);
    return await response.value();
  }
}
