/**
 * Nager.Date API Reference
 * The Nager.Date API is a free public service that provides reliable information about public holidays and long weekends for countries around the world. It allows developers to query national holiday dates, check whether a specific day is a public holiday, list upcoming holidays, and explore long-weekend data.    By using the API, you agree to the <a href=\"https://date.nager.at/Legal/TermsOfService\">Terms of Service.</a>
 *
 * The version of the OpenAPI document: v3
 * Contact: hello@nager.software
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import CountryInfoDto from './model/CountryInfoDto';
import CountryInfoWithBordersDto from './model/CountryInfoWithBordersDto';
import CountryV3Dto from './model/CountryV3Dto';
import HolidayTypes from './model/HolidayTypes';
import LongWeekendV3Dto from './model/LongWeekendV3Dto';
import ProblemDetails from './model/ProblemDetails';
import PublicHolidayV3Dto from './model/PublicHolidayV3Dto';
import VersionInfoDto from './model/VersionInfoDto';
import CountryApi from './api/CountryApi';
import LongWeekendApi from './api/LongWeekendApi';
import PublicHolidayApi from './api/PublicHolidayApi';
import VersionApi from './api/VersionApi';


/**
* The Nager.Date API is a free public service that provides reliable information about public holidays and long weekends for countries around the world. It allows developers to query national holiday dates, check whether a specific day is a public holiday, list upcoming holidays, and explore long-weekend data.    By using the API, you agree to the &lt;a href&#x3D;\&quot;https://date.nager.at/Legal/TermsOfService\&quot;&gt;Terms of Service.&lt;/a&gt;.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var NagerDateApiReference = require('index'); // See note below*.
* var xxxSvc = new NagerDateApiReference.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new NagerDateApiReference.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new NagerDateApiReference.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new NagerDateApiReference.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version v3
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The CountryInfoDto model constructor.
     * @property {module:model/CountryInfoDto}
     */
    CountryInfoDto,

    /**
     * The CountryInfoWithBordersDto model constructor.
     * @property {module:model/CountryInfoWithBordersDto}
     */
    CountryInfoWithBordersDto,

    /**
     * The CountryV3Dto model constructor.
     * @property {module:model/CountryV3Dto}
     */
    CountryV3Dto,

    /**
     * The HolidayTypes model constructor.
     * @property {module:model/HolidayTypes}
     */
    HolidayTypes,

    /**
     * The LongWeekendV3Dto model constructor.
     * @property {module:model/LongWeekendV3Dto}
     */
    LongWeekendV3Dto,

    /**
     * The ProblemDetails model constructor.
     * @property {module:model/ProblemDetails}
     */
    ProblemDetails,

    /**
     * The PublicHolidayV3Dto model constructor.
     * @property {module:model/PublicHolidayV3Dto}
     */
    PublicHolidayV3Dto,

    /**
     * The VersionInfoDto model constructor.
     * @property {module:model/VersionInfoDto}
     */
    VersionInfoDto,

    /**
    * The CountryApi service constructor.
    * @property {module:api/CountryApi}
    */
    CountryApi,

    /**
    * The LongWeekendApi service constructor.
    * @property {module:api/LongWeekendApi}
    */
    LongWeekendApi,

    /**
    * The PublicHolidayApi service constructor.
    * @property {module:api/PublicHolidayApi}
    */
    PublicHolidayApi,

    /**
    * The VersionApi service constructor.
    * @property {module:api/VersionApi}
    */
    VersionApi
};
