/**
 * Nager.Date API Reference
 * The Nager.Date API is a free public service that provides reliable information about public holidays and long weekends for countries around the world. It allows developers to query national holiday dates, check whether a specific day is a public holiday, list upcoming holidays, and explore long-weekend data.    By using the API, you agree to the <a href=\"https://date.nager.at/Legal/TermsOfService\">Terms of Service.</a>
 *
 * The version of the OpenAPI document: v3
 * Contact: hello@nager.software
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CountryInfoWithBordersDto from '../model/CountryInfoWithBordersDto';
import CountryV3Dto from '../model/CountryV3Dto';
import ProblemDetails from '../model/ProblemDetails';

/**
* Country service.
* @module api/CountryApi
* @version v3
*/
export default class CountryApi {

    /**
    * Constructs a new CountryApi. 
    * @alias module:api/CountryApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the apiV3AvailableCountriesGet operation.
     * @callback module:api/CountryApi~apiV3AvailableCountriesGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/CountryV3Dto>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve the complete list of all countries supported by the Nager.Date API
     * This endpoint returns all countries for which public-holiday data is available. Each entry includes the country's name and ISO code.
     * @param {module:api/CountryApi~apiV3AvailableCountriesGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/CountryV3Dto>}
     */
    apiV3AvailableCountriesGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [CountryV3Dto];
      return this.apiClient.callApi(
        '/api/v3/AvailableCountries', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the apiV3CountryInfoCountryCodeGet operation.
     * @callback module:api/CountryApi~apiV3CountryInfoCountryCodeGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CountryInfoWithBordersDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieves detailed information about a specific country
     * Provide a valid `ISO 3166-1 alpha-2` country code to retrieve country metadata. The response includes commonly used and official country names, the assigned region, and if available neighboring countries based on geographical borders.
     * @param {String} countryCode The 2-letter ISO 3166-1 country code (e.g., \"US\", \"GB\").
     * @param {module:api/CountryApi~apiV3CountryInfoCountryCodeGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CountryInfoWithBordersDto}
     */
    apiV3CountryInfoCountryCodeGet(countryCode, callback) {
      let postBody = null;
      // verify the required parameter 'countryCode' is set
      if (countryCode === undefined || countryCode === null) {
        throw new Error("Missing the required parameter 'countryCode' when calling apiV3CountryInfoCountryCodeGet");
      }

      let pathParams = {
        'countryCode': countryCode
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = CountryInfoWithBordersDto;
      return this.apiClient.callApi(
        '/api/v3/CountryInfo/{countryCode}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
