/**
 * Nager.Date API Reference
 * The Nager.Date API is a free public service that provides reliable information about public holidays and long weekends for countries around the world. It allows developers to query national holiday dates, check whether a specific day is a public holiday, list upcoming holidays, and explore long-weekend data.    By using the API, you agree to the <a href=\"https://date.nager.at/Legal/TermsOfService\">Terms of Service.</a>
 *
 * The version of the OpenAPI document: v3
 * Contact: hello@nager.software
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import LongWeekendV3Dto from '../model/LongWeekendV3Dto';
import ProblemDetails from '../model/ProblemDetails';

/**
* LongWeekend service.
* @module api/LongWeekendApi
* @version v3
*/
export default class LongWeekendApi {

    /**
    * Constructs a new LongWeekendApi. 
    * @alias module:api/LongWeekendApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the apiV3LongWeekendYearCountryCodeGet operation.
     * @callback module:api/LongWeekendApi~apiV3LongWeekendYearCountryCodeGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/LongWeekendV3Dto>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve all long weekends for a given country and year
     * A long weekend is calculated based on public holidays that create an extended break of at least three consecutive days. Optional bridge days-weekdays between a holiday and a weekend-can be included to identify potential extended leave opportunities.
     * @param {Number} year The target year for which long-weekend data should be calculated.
     * @param {String} countryCode A valid `ISO 3166-1 alpha-2` country code determining the region of interest.
     * @param {Object} opts Optional parameters
     * @param {Number} [availableBridgeDays = 1)] The maximum number of bridge days to include when determining long-weekend opportunities.
     * @param {String} [subdivisionCode] Narrow the calculation to a specific federal state, province, or subdivision (where supported).
     * @param {module:api/LongWeekendApi~apiV3LongWeekendYearCountryCodeGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/LongWeekendV3Dto>}
     */
    apiV3LongWeekendYearCountryCodeGet(year, countryCode, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'year' is set
      if (year === undefined || year === null) {
        throw new Error("Missing the required parameter 'year' when calling apiV3LongWeekendYearCountryCodeGet");
      }
      // verify the required parameter 'countryCode' is set
      if (countryCode === undefined || countryCode === null) {
        throw new Error("Missing the required parameter 'countryCode' when calling apiV3LongWeekendYearCountryCodeGet");
      }

      let pathParams = {
        'year': year,
        'countryCode': countryCode
      };
      let queryParams = {
        'availableBridgeDays': opts['availableBridgeDays'],
        'subdivisionCode': opts['subdivisionCode']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [LongWeekendV3Dto];
      return this.apiClient.callApi(
        '/api/v3/LongWeekend/{year}/{countryCode}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
