/**
 * Nager.Date API Reference
 * The Nager.Date API is a free public service that provides reliable information about public holidays and long weekends for countries around the world. It allows developers to query national holiday dates, check whether a specific day is a public holiday, list upcoming holidays, and explore long-weekend data.    By using the API, you agree to the <a href=\"https://date.nager.at/Legal/TermsOfService\">Terms of Service.</a>
 *
 * The version of the OpenAPI document: v3
 * Contact: hello@nager.software
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ProblemDetails from '../model/ProblemDetails';
import PublicHolidayV3Dto from '../model/PublicHolidayV3Dto';

/**
* PublicHoliday service.
* @module api/PublicHolidayApi
* @version v3
*/
export default class PublicHolidayApi {

    /**
    * Constructs a new PublicHolidayApi. 
    * @alias module:api/PublicHolidayApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the apiV3IsTodayPublicHolidayCountryCodeGet operation.
     * @callback module:api/PublicHolidayApi~apiV3IsTodayPublicHolidayCountryCodeGetCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Determines whether today is a public holiday in the specified country, optionally adjusted by a UTC offset
     * By default, the calculation is based on the current UTC date. You may optionally provide a timezone offset to evaluate the holiday status relative to a different local timezone.  This endpoint is optimized for simple command-line or automation workflows where only the HTTP status code is required  ``` STATUSCODE=$(curl --silent --output /dev/stderr --write-out \"%{http_code}\" https://date.nager.at/Api/v3/IsTodayPublicHoliday/AT) if [ $STATUSCODE -ne 200 ]; then     # handle error fi ```
     * @param {String} countryCode A valid `ISO 3166-1 alpha-2` country code.
     * @param {Object} opts Optional parameters
     * @param {String} [countyCode] Optional. The subdivision code (e.g., state, province) to narrow the check.
     * @param {Number} [offset = 0)] Optional. UTC timezone offset in hours (range: -12 to +12).
     * @param {module:api/PublicHolidayApi~apiV3IsTodayPublicHolidayCountryCodeGetCallback} callback The callback function, accepting three arguments: error, data, response
     */
    apiV3IsTodayPublicHolidayCountryCodeGet(countryCode, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'countryCode' is set
      if (countryCode === undefined || countryCode === null) {
        throw new Error("Missing the required parameter 'countryCode' when calling apiV3IsTodayPublicHolidayCountryCodeGet");
      }

      let pathParams = {
        'countryCode': countryCode
      };
      let queryParams = {
        'countyCode': opts['countyCode'],
        'offset': opts['offset']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v3/IsTodayPublicHoliday/{countryCode}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the apiV3NextPublicHolidaysCountryCodeGet operation.
     * @callback module:api/PublicHolidayApi~apiV3NextPublicHolidaysCountryCodeGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/PublicHolidayV3Dto>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve all upcoming public holidays occurring within the next 365 days for a given country
     * The list includes only future holidays relative to the current date and is useful for forecasting, event planning, and applications that provide forward-looking holiday insights.
     * @param {String} countryCode A valid `ISO 3166-1 alpha-2` country code.
     * @param {module:api/PublicHolidayApi~apiV3NextPublicHolidaysCountryCodeGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/PublicHolidayV3Dto>}
     */
    apiV3NextPublicHolidaysCountryCodeGet(countryCode, callback) {
      let postBody = null;
      // verify the required parameter 'countryCode' is set
      if (countryCode === undefined || countryCode === null) {
        throw new Error("Missing the required parameter 'countryCode' when calling apiV3NextPublicHolidaysCountryCodeGet");
      }

      let pathParams = {
        'countryCode': countryCode
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [PublicHolidayV3Dto];
      return this.apiClient.callApi(
        '/api/v3/NextPublicHolidays/{countryCode}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the apiV3NextPublicHolidaysWorldwideGet operation.
     * @callback module:api/PublicHolidayApi~apiV3NextPublicHolidaysWorldwideGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/PublicHolidayV3Dto>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve all public holidays occurring worldwide within the next 7 days
     * This global endpoint aggregates upcoming holidays across all supported countries, enabling international systems to detect near-term events.
     * @param {module:api/PublicHolidayApi~apiV3NextPublicHolidaysWorldwideGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/PublicHolidayV3Dto>}
     */
    apiV3NextPublicHolidaysWorldwideGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [PublicHolidayV3Dto];
      return this.apiClient.callApi(
        '/api/v3/NextPublicHolidaysWorldwide', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the apiV3PublicHolidaysYearCountryCodeGet operation.
     * @callback module:api/PublicHolidayApi~apiV3PublicHolidaysYearCountryCodeGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/PublicHolidayV3Dto>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve the list of all public holidays for the specified year and country
     * This endpoint returns all officially recognized public holidays for the given country and year. Each holiday entry includes the local and English holiday names, information about whether the holiday applies nationally or only in specific subdivisions, and the associated holiday type classifications.
     * @param {Number} year The target year for which public holidays should be retrieved.
     * @param {String} countryCode A valid `ISO 3166-1 alpha-2` country code.
     * @param {module:api/PublicHolidayApi~apiV3PublicHolidaysYearCountryCodeGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/PublicHolidayV3Dto>}
     */
    apiV3PublicHolidaysYearCountryCodeGet(year, countryCode, callback) {
      let postBody = null;
      // verify the required parameter 'year' is set
      if (year === undefined || year === null) {
        throw new Error("Missing the required parameter 'year' when calling apiV3PublicHolidaysYearCountryCodeGet");
      }
      // verify the required parameter 'countryCode' is set
      if (countryCode === undefined || countryCode === null) {
        throw new Error("Missing the required parameter 'countryCode' when calling apiV3PublicHolidaysYearCountryCodeGet");
      }

      let pathParams = {
        'year': year,
        'countryCode': countryCode
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [PublicHolidayV3Dto];
      return this.apiClient.callApi(
        '/api/v3/PublicHolidays/{year}/{countryCode}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
