/**
 * Nager.Date API Reference
 * The Nager.Date API is a free public service that provides reliable information about public holidays and long weekends for countries around the world. It allows developers to query national holiday dates, check whether a specific day is a public holiday, list upcoming holidays, and explore long-weekend data.    By using the API, you agree to the <a href=\"https://date.nager.at/Legal/TermsOfService\">Terms of Service.</a>
 *
 * The version of the OpenAPI document: v3
 * Contact: hello@nager.software
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import VersionInfoDto from '../model/VersionInfoDto';

/**
* Version service.
* @module api/VersionApi
* @version v3
*/
export default class VersionApi {

    /**
    * Constructs a new VersionApi. 
    * @alias module:api/VersionApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the apiV3VersionGet operation.
     * @callback module:api/VersionApi~apiV3VersionGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/VersionInfoDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve the current version information of the Nager.Date library
     * This endpoint returns detailed version information about the Nager.Date implementation running on the server, including the exact NuGet package version used by the API.
     * @param {module:api/VersionApi~apiV3VersionGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/VersionInfoDto}
     */
    apiV3VersionGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = VersionInfoDto;
      return this.apiClient.callApi(
        '/api/v3/Version', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
