/**
 * Nager.Date API Reference
 * The Nager.Date API is a free public service that provides reliable information about public holidays and long weekends for countries around the world. It allows developers to query national holiday dates, check whether a specific day is a public holiday, list upcoming holidays, and explore long-weekend data.    By using the API, you agree to the <a href=\"https://date.nager.at/Legal/TermsOfService\">Terms of Service.</a>
 *
 * The version of the OpenAPI document: v3
 * Contact: hello@nager.software
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CountryInfoDto model module.
 * @module model/CountryInfoDto
 * @version v3
 */
class CountryInfoDto {
    /**
     * Constructs a new <code>CountryInfoDto</code>.
     * Detailed information about a country.
     * @alias module:model/CountryInfoDto
     * @param commonName {String} The commonly used name of the country.
     * @param officialName {String} The official name of the country.
     * @param countryCode {String} ISO 3166-1 alpha-2 country code.
     * @param region {String} Geopolitical or continental region of the country.
     */
    constructor(commonName, officialName, countryCode, region) { 
        
        CountryInfoDto.initialize(this, commonName, officialName, countryCode, region);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, commonName, officialName, countryCode, region) { 
        obj['commonName'] = commonName;
        obj['officialName'] = officialName;
        obj['countryCode'] = countryCode;
        obj['region'] = region;
    }

    /**
     * Constructs a <code>CountryInfoDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CountryInfoDto} obj Optional instance to populate.
     * @return {module:model/CountryInfoDto} The populated <code>CountryInfoDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CountryInfoDto();

            if (data.hasOwnProperty('commonName')) {
                obj['commonName'] = ApiClient.convertToType(data['commonName'], 'String');
            }
            if (data.hasOwnProperty('officialName')) {
                obj['officialName'] = ApiClient.convertToType(data['officialName'], 'String');
            }
            if (data.hasOwnProperty('countryCode')) {
                obj['countryCode'] = ApiClient.convertToType(data['countryCode'], 'String');
            }
            if (data.hasOwnProperty('region')) {
                obj['region'] = ApiClient.convertToType(data['region'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CountryInfoDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CountryInfoDto</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CountryInfoDto.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['commonName'] && !(typeof data['commonName'] === 'string' || data['commonName'] instanceof String)) {
            throw new Error("Expected the field `commonName` to be a primitive type in the JSON string but got " + data['commonName']);
        }
        // ensure the json data is a string
        if (data['officialName'] && !(typeof data['officialName'] === 'string' || data['officialName'] instanceof String)) {
            throw new Error("Expected the field `officialName` to be a primitive type in the JSON string but got " + data['officialName']);
        }
        // ensure the json data is a string
        if (data['countryCode'] && !(typeof data['countryCode'] === 'string' || data['countryCode'] instanceof String)) {
            throw new Error("Expected the field `countryCode` to be a primitive type in the JSON string but got " + data['countryCode']);
        }
        // ensure the json data is a string
        if (data['region'] && !(typeof data['region'] === 'string' || data['region'] instanceof String)) {
            throw new Error("Expected the field `region` to be a primitive type in the JSON string but got " + data['region']);
        }

        return true;
    }


}

CountryInfoDto.RequiredProperties = ["commonName", "officialName", "countryCode", "region"];

/**
 * The commonly used name of the country.
 * @member {String} commonName
 */
CountryInfoDto.prototype['commonName'] = undefined;

/**
 * The official name of the country.
 * @member {String} officialName
 */
CountryInfoDto.prototype['officialName'] = undefined;

/**
 * ISO 3166-1 alpha-2 country code.
 * @member {String} countryCode
 */
CountryInfoDto.prototype['countryCode'] = undefined;

/**
 * Geopolitical or continental region of the country.
 * @member {String} region
 */
CountryInfoDto.prototype['region'] = undefined;






export default CountryInfoDto;

