/**
 * Nager.Date API Reference
 * The Nager.Date API is a free public service that provides reliable information about public holidays and long weekends for countries around the world. It allows developers to query national holiday dates, check whether a specific day is a public holiday, list upcoming holidays, and explore long-weekend data.    By using the API, you agree to the <a href=\"https://date.nager.at/Legal/TermsOfService\">Terms of Service.</a>
 *
 * The version of the OpenAPI document: v3
 * Contact: hello@nager.software
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CountryV3Dto model module.
 * @module model/CountryV3Dto
 * @version v3
 */
class CountryV3Dto {
    /**
     * Constructs a new <code>CountryV3Dto</code>.
     * Represents a country supported by the Nager.Date API.
     * @alias module:model/CountryV3Dto
     * @param countryCode {String} The ISO 3166-1 alpha-2 country code (e.g., \"US\", \"DE\").
     * @param name {String} The common name of the country.
     */
    constructor(countryCode, name) { 
        
        CountryV3Dto.initialize(this, countryCode, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, countryCode, name) { 
        obj['countryCode'] = countryCode;
        obj['name'] = name;
    }

    /**
     * Constructs a <code>CountryV3Dto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CountryV3Dto} obj Optional instance to populate.
     * @return {module:model/CountryV3Dto} The populated <code>CountryV3Dto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CountryV3Dto();

            if (data.hasOwnProperty('countryCode')) {
                obj['countryCode'] = ApiClient.convertToType(data['countryCode'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CountryV3Dto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CountryV3Dto</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CountryV3Dto.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['countryCode'] && !(typeof data['countryCode'] === 'string' || data['countryCode'] instanceof String)) {
            throw new Error("Expected the field `countryCode` to be a primitive type in the JSON string but got " + data['countryCode']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }

        return true;
    }


}

CountryV3Dto.RequiredProperties = ["countryCode", "name"];

/**
 * The ISO 3166-1 alpha-2 country code (e.g., \"US\", \"DE\").
 * @member {String} countryCode
 */
CountryV3Dto.prototype['countryCode'] = undefined;

/**
 * The common name of the country.
 * @member {String} name
 */
CountryV3Dto.prototype['name'] = undefined;






export default CountryV3Dto;

