/**
 * Nager.Date API Reference
 * The Nager.Date API is a free public service that provides reliable information about public holidays and long weekends for countries around the world. It allows developers to query national holiday dates, check whether a specific day is a public holiday, list upcoming holidays, and explore long-weekend data.    By using the API, you agree to the <a href=\"https://date.nager.at/Legal/TermsOfService\">Terms of Service.</a>
 *
 * The version of the OpenAPI document: v3
 * Contact: hello@nager.software
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class HolidayTypes.
* @enum {}
* @readonly
*/
export default class HolidayTypes {
    
        /**
         * value: "Public"
         * @const
         */
        "Public" = "Public";

    
        /**
         * value: "Bank"
         * @const
         */
        "Bank" = "Bank";

    
        /**
         * value: "School"
         * @const
         */
        "School" = "School";

    
        /**
         * value: "Authorities"
         * @const
         */
        "Authorities" = "Authorities";

    
        /**
         * value: "Optional"
         * @const
         */
        "Optional" = "Optional";

    
        /**
         * value: "Observance"
         * @const
         */
        "Observance" = "Observance";

    

    /**
    * Returns a <code>HolidayTypes</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/HolidayTypes} The enum <code>HolidayTypes</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

