/**
 * Nager.Date API Reference
 * The Nager.Date API is a free public service that provides reliable information about public holidays and long weekends for countries around the world. It allows developers to query national holiday dates, check whether a specific day is a public holiday, list upcoming holidays, and explore long-weekend data.    By using the API, you agree to the <a href=\"https://date.nager.at/Legal/TermsOfService\">Terms of Service.</a>
 *
 * The version of the OpenAPI document: v3
 * Contact: hello@nager.software
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LongWeekendV3Dto model module.
 * @module model/LongWeekendV3Dto
 * @version v3
 */
class LongWeekendV3Dto {
    /**
     * Constructs a new <code>LongWeekendV3Dto</code>.
     * Represents a long weekend, including optional bridge days.
     * @alias module:model/LongWeekendV3Dto
     */
    constructor() { 
        
        LongWeekendV3Dto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LongWeekendV3Dto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LongWeekendV3Dto} obj Optional instance to populate.
     * @return {module:model/LongWeekendV3Dto} The populated <code>LongWeekendV3Dto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LongWeekendV3Dto();

            if (data.hasOwnProperty('startDate')) {
                obj['startDate'] = ApiClient.convertToType(data['startDate'], 'Date');
            }
            if (data.hasOwnProperty('endDate')) {
                obj['endDate'] = ApiClient.convertToType(data['endDate'], 'Date');
            }
            if (data.hasOwnProperty('dayCount')) {
                obj['dayCount'] = ApiClient.convertToType(data['dayCount'], 'Number');
            }
            if (data.hasOwnProperty('needBridgeDay')) {
                obj['needBridgeDay'] = ApiClient.convertToType(data['needBridgeDay'], 'Boolean');
            }
            if (data.hasOwnProperty('bridgeDays')) {
                obj['bridgeDays'] = ApiClient.convertToType(data['bridgeDays'], ['Date']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>LongWeekendV3Dto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>LongWeekendV3Dto</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['bridgeDays'])) {
            throw new Error("Expected the field `bridgeDays` to be an array in the JSON data but got " + data['bridgeDays']);
        }

        return true;
    }


}



/**
 * The start date of the long weekend.
 * @member {Date} startDate
 */
LongWeekendV3Dto.prototype['startDate'] = undefined;

/**
 * The end date of the long weekend.
 * @member {Date} endDate
 */
LongWeekendV3Dto.prototype['endDate'] = undefined;

/**
 * Total number of days in the long weekend.
 * @member {Number} dayCount
 */
LongWeekendV3Dto.prototype['dayCount'] = undefined;

/**
 * Indicates whether a bridge day is required to achieve the long weekend.
 * @member {Boolean} needBridgeDay
 */
LongWeekendV3Dto.prototype['needBridgeDay'] = undefined;

/**
 * Optional bridge days that extend the weekend.
 * @member {Array.<Date>} bridgeDays
 */
LongWeekendV3Dto.prototype['bridgeDays'] = undefined;






export default LongWeekendV3Dto;

