/**
 * Nager.Date API Reference
 * The Nager.Date API is a free public service that provides reliable information about public holidays and long weekends for countries around the world. It allows developers to query national holiday dates, check whether a specific day is a public holiday, list upcoming holidays, and explore long-weekend data.    By using the API, you agree to the <a href=\"https://date.nager.at/Legal/TermsOfService\">Terms of Service.</a>
 *
 * The version of the OpenAPI document: v3
 * Contact: hello@nager.software
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import HolidayTypes from './HolidayTypes';

/**
 * The PublicHolidayV3Dto model module.
 * @module model/PublicHolidayV3Dto
 * @version v3
 */
class PublicHolidayV3Dto {
    /**
     * Constructs a new <code>PublicHolidayV3Dto</code>.
     * Represents a public holiday.
     * @alias module:model/PublicHolidayV3Dto
     * @param date {Date} The date of the holiday.
     * @param localName {String} Local name of the holiday.
     * @param name {String} English name of the holiday.
     * @param countryCode {String} ISO 3166-1 alpha-2 country code.
     * @param types {Array.<module:model/HolidayTypes>} List of holiday types this holiday is classified under.
     */
    constructor(date, localName, name, countryCode, types) { 
        
        PublicHolidayV3Dto.initialize(this, date, localName, name, countryCode, types);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, date, localName, name, countryCode, types) { 
        obj['date'] = date;
        obj['localName'] = localName;
        obj['name'] = name;
        obj['countryCode'] = countryCode;
        obj['types'] = types;
    }

    /**
     * Constructs a <code>PublicHolidayV3Dto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PublicHolidayV3Dto} obj Optional instance to populate.
     * @return {module:model/PublicHolidayV3Dto} The populated <code>PublicHolidayV3Dto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PublicHolidayV3Dto();

            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Date');
            }
            if (data.hasOwnProperty('localName')) {
                obj['localName'] = ApiClient.convertToType(data['localName'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('countryCode')) {
                obj['countryCode'] = ApiClient.convertToType(data['countryCode'], 'String');
            }
            if (data.hasOwnProperty('fixed')) {
                obj['fixed'] = ApiClient.convertToType(data['fixed'], 'Boolean');
            }
            if (data.hasOwnProperty('global')) {
                obj['global'] = ApiClient.convertToType(data['global'], 'Boolean');
            }
            if (data.hasOwnProperty('counties')) {
                obj['counties'] = ApiClient.convertToType(data['counties'], ['String']);
            }
            if (data.hasOwnProperty('launchYear')) {
                obj['launchYear'] = ApiClient.convertToType(data['launchYear'], 'Number');
            }
            if (data.hasOwnProperty('types')) {
                obj['types'] = ApiClient.convertToType(data['types'], [HolidayTypes]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PublicHolidayV3Dto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PublicHolidayV3Dto</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PublicHolidayV3Dto.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['localName'] && !(typeof data['localName'] === 'string' || data['localName'] instanceof String)) {
            throw new Error("Expected the field `localName` to be a primitive type in the JSON string but got " + data['localName']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['countryCode'] && !(typeof data['countryCode'] === 'string' || data['countryCode'] instanceof String)) {
            throw new Error("Expected the field `countryCode` to be a primitive type in the JSON string but got " + data['countryCode']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['counties'])) {
            throw new Error("Expected the field `counties` to be an array in the JSON data but got " + data['counties']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['types'])) {
            throw new Error("Expected the field `types` to be an array in the JSON data but got " + data['types']);
        }

        return true;
    }


}

PublicHolidayV3Dto.RequiredProperties = ["date", "localName", "name", "countryCode", "types"];

/**
 * The date of the holiday.
 * @member {Date} date
 */
PublicHolidayV3Dto.prototype['date'] = undefined;

/**
 * Local name of the holiday.
 * @member {String} localName
 */
PublicHolidayV3Dto.prototype['localName'] = undefined;

/**
 * English name of the holiday.
 * @member {String} name
 */
PublicHolidayV3Dto.prototype['name'] = undefined;

/**
 * ISO 3166-1 alpha-2 country code.
 * @member {String} countryCode
 */
PublicHolidayV3Dto.prototype['countryCode'] = undefined;

/**
 * Indicates if this holiday occurs on the same date every year.
 * @member {Boolean} fixed
 */
PublicHolidayV3Dto.prototype['fixed'] = undefined;

/**
 * Indicates if this holiday applies to the entire country.
 * @member {Boolean} global
 */
PublicHolidayV3Dto.prototype['global'] = undefined;

/**
 * ISO-3166-2 codes of the subdivisions where this holiday applies
 * @member {Array.<String>} counties
 */
PublicHolidayV3Dto.prototype['counties'] = undefined;

/**
 * The year the holiday was first observed.
 * @member {Number} launchYear
 */
PublicHolidayV3Dto.prototype['launchYear'] = undefined;

/**
 * List of holiday types this holiday is classified under.
 * @member {Array.<module:model/HolidayTypes>} types
 */
PublicHolidayV3Dto.prototype['types'] = undefined;






export default PublicHolidayV3Dto;

