/* tslint:disable */
/* eslint-disable */
/**
 * Nager.Date API Reference
 * The Nager.Date API is a free public service that provides reliable information about public holidays and long weekends for countries around the world. It allows developers to query national holiday dates, check whether a specific day is a public holiday, list upcoming holidays, and explore long-weekend data.    By using the API, you agree to the <a href=\"https://date.nager.at/Legal/TermsOfService\">Terms of Service.</a>
 *
 * The version of the OpenAPI document: v3
 * Contact: hello@nager.software
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * Represents a country supported by the Nager.Date API.
 * @export
 * @interface CountryV3Dto
 */
export interface CountryV3Dto {
  /**
   * The ISO 3166-1 alpha-2 country code (e.g., "US", "DE").
   * @type {string}
   * @memberof CountryV3Dto
   */
  countryCode: string;
  /**
   * The common name of the country.
   * @type {string}
   * @memberof CountryV3Dto
   */
  name: string;
}

/**
 * Check if a given object implements the CountryV3Dto interface.
 */
export function instanceOfCountryV3Dto(value: object): value is CountryV3Dto {
  if (!("countryCode" in value) || value["countryCode"] === undefined)
    return false;
  if (!("name" in value) || value["name"] === undefined) return false;
  return true;
}

export function CountryV3DtoFromJSON(json: any): CountryV3Dto {
  return CountryV3DtoFromJSONTyped(json, false);
}

export function CountryV3DtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CountryV3Dto {
  if (json == null) {
    return json;
  }
  return {
    countryCode: json["countryCode"],
    name: json["name"],
  };
}

export function CountryV3DtoToJSON(json: any): CountryV3Dto {
  return CountryV3DtoToJSONTyped(json, false);
}

export function CountryV3DtoToJSONTyped(
  value?: CountryV3Dto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    countryCode: value["countryCode"],
    name: value["name"],
  };
}
