/* tslint:disable */
/* eslint-disable */
/**
 * Nager.Date API Reference
 * The Nager.Date API is a free public service that provides reliable information about public holidays and long weekends for countries around the world. It allows developers to query national holiday dates, check whether a specific day is a public holiday, list upcoming holidays, and explore long-weekend data.    By using the API, you agree to the <a href=\"https://date.nager.at/Legal/TermsOfService\">Terms of Service.</a>
 *
 * The version of the OpenAPI document: v3
 * Contact: hello@nager.software
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const HolidayTypes = {
    Public: 'Public',
    Bank: 'Bank',
    School: 'School',
    Authorities: 'Authorities',
    Optional: 'Optional',
    Observance: 'Observance'
} as const;
export type HolidayTypes = typeof HolidayTypes[keyof typeof HolidayTypes];


export function instanceOfHolidayTypes(value: any): boolean {
    for (const key in HolidayTypes) {
        if (Object.prototype.hasOwnProperty.call(HolidayTypes, key)) {
            if (HolidayTypes[key as keyof typeof HolidayTypes] === value) {
                return true;
            }
        }
    }
    return false;
}

export function HolidayTypesFromJSON(json: any): HolidayTypes {
    return HolidayTypesFromJSONTyped(json, false);
}

export function HolidayTypesFromJSONTyped(json: any, ignoreDiscriminator: boolean): HolidayTypes {
    return json as HolidayTypes;
}

export function HolidayTypesToJSON(value?: HolidayTypes | null): any {
    return value as any;
}

export function HolidayTypesToJSONTyped(value: any, ignoreDiscriminator: boolean): HolidayTypes {
    return value as HolidayTypes;
}

