/* tslint:disable */
/* eslint-disable */
/**
 * Nager.Date API Reference
 * The Nager.Date API is a free public service that provides reliable information about public holidays and long weekends for countries around the world. It allows developers to query national holiday dates, check whether a specific day is a public holiday, list upcoming holidays, and explore long-weekend data.    By using the API, you agree to the <a href=\"https://date.nager.at/Legal/TermsOfService\">Terms of Service.</a>
 *
 * The version of the OpenAPI document: v3
 * Contact: hello@nager.software
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * Version information.
 * @export
 * @interface VersionInfoDto
 */
export interface VersionInfoDto {
  /**
   * The name of the library.
   * @type {string}
   * @memberof VersionInfoDto
   */
  name: string;
  /**
   * The version of the library.
   * @type {string}
   * @memberof VersionInfoDto
   */
  version: string;
}

/**
 * Check if a given object implements the VersionInfoDto interface.
 */
export function instanceOfVersionInfoDto(
  value: object,
): value is VersionInfoDto {
  if (!("name" in value) || value["name"] === undefined) return false;
  if (!("version" in value) || value["version"] === undefined) return false;
  return true;
}

export function VersionInfoDtoFromJSON(json: any): VersionInfoDto {
  return VersionInfoDtoFromJSONTyped(json, false);
}

export function VersionInfoDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): VersionInfoDto {
  if (json == null) {
    return json;
  }
  return {
    name: json["name"],
    version: json["version"],
  };
}

export function VersionInfoDtoToJSON(json: any): VersionInfoDto {
  return VersionInfoDtoToJSONTyped(json, false);
}

export function VersionInfoDtoToJSONTyped(
  value?: VersionInfoDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value["name"],
    version: value["version"],
  };
}
