/**
 * Nager.Date API Reference
 * The Nager.Date API is a free public service that provides reliable information about public holidays and long weekends for countries around the world. It allows developers to query national holiday dates, check whether a specific day is a public holiday, list upcoming holidays, and explore long-weekend data.    By using the API, you agree to the <a href=\"https://date.nager.at/Legal/TermsOfService\">Terms of Service.</a>
 *
 * The version of the OpenAPI document: v3
 * Contact: hello@nager.software
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NagerDateApiReference);
  }
}(this, function(expect, NagerDateApiReference) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NagerDateApiReference.CountryInfoWithBordersDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CountryInfoWithBordersDto', function() {
    it('should create an instance of CountryInfoWithBordersDto', function() {
      // uncomment below and update the code to test CountryInfoWithBordersDto
      //var instance = new NagerDateApiReference.CountryInfoWithBordersDto();
      //expect(instance).to.be.a(NagerDateApiReference.CountryInfoWithBordersDto);
    });

    it('should have the property commonName (base name: "commonName")', function() {
      // uncomment below and update the code to test the property commonName
      //var instance = new NagerDateApiReference.CountryInfoWithBordersDto();
      //expect(instance).to.be();
    });

    it('should have the property officialName (base name: "officialName")', function() {
      // uncomment below and update the code to test the property officialName
      //var instance = new NagerDateApiReference.CountryInfoWithBordersDto();
      //expect(instance).to.be();
    });

    it('should have the property countryCode (base name: "countryCode")', function() {
      // uncomment below and update the code to test the property countryCode
      //var instance = new NagerDateApiReference.CountryInfoWithBordersDto();
      //expect(instance).to.be();
    });

    it('should have the property region (base name: "region")', function() {
      // uncomment below and update the code to test the property region
      //var instance = new NagerDateApiReference.CountryInfoWithBordersDto();
      //expect(instance).to.be();
    });

    it('should have the property borders (base name: "borders")', function() {
      // uncomment below and update the code to test the property borders
      //var instance = new NagerDateApiReference.CountryInfoWithBordersDto();
      //expect(instance).to.be();
    });

  });

}));
