/**
 * Nager.Date API Reference
 * The Nager.Date API is a free public service that provides reliable information about public holidays and long weekends for countries around the world. It allows developers to query national holiday dates, check whether a specific day is a public holiday, list upcoming holidays, and explore long-weekend data.    By using the API, you agree to the <a href=\"https://date.nager.at/Legal/TermsOfService\">Terms of Service.</a>
 *
 * The version of the OpenAPI document: v3
 * Contact: hello@nager.software
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NagerDateApiReference);
  }
}(this, function(expect, NagerDateApiReference) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NagerDateApiReference.PublicHolidayV3Dto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PublicHolidayV3Dto', function() {
    it('should create an instance of PublicHolidayV3Dto', function() {
      // uncomment below and update the code to test PublicHolidayV3Dto
      //var instance = new NagerDateApiReference.PublicHolidayV3Dto();
      //expect(instance).to.be.a(NagerDateApiReference.PublicHolidayV3Dto);
    });

    it('should have the property date (base name: "date")', function() {
      // uncomment below and update the code to test the property date
      //var instance = new NagerDateApiReference.PublicHolidayV3Dto();
      //expect(instance).to.be();
    });

    it('should have the property localName (base name: "localName")', function() {
      // uncomment below and update the code to test the property localName
      //var instance = new NagerDateApiReference.PublicHolidayV3Dto();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new NagerDateApiReference.PublicHolidayV3Dto();
      //expect(instance).to.be();
    });

    it('should have the property countryCode (base name: "countryCode")', function() {
      // uncomment below and update the code to test the property countryCode
      //var instance = new NagerDateApiReference.PublicHolidayV3Dto();
      //expect(instance).to.be();
    });

    it('should have the property fixed (base name: "fixed")', function() {
      // uncomment below and update the code to test the property fixed
      //var instance = new NagerDateApiReference.PublicHolidayV3Dto();
      //expect(instance).to.be();
    });

    it('should have the property global (base name: "global")', function() {
      // uncomment below and update the code to test the property global
      //var instance = new NagerDateApiReference.PublicHolidayV3Dto();
      //expect(instance).to.be();
    });

    it('should have the property counties (base name: "counties")', function() {
      // uncomment below and update the code to test the property counties
      //var instance = new NagerDateApiReference.PublicHolidayV3Dto();
      //expect(instance).to.be();
    });

    it('should have the property launchYear (base name: "launchYear")', function() {
      // uncomment below and update the code to test the property launchYear
      //var instance = new NagerDateApiReference.PublicHolidayV3Dto();
      //expect(instance).to.be();
    });

    it('should have the property types (base name: "types")', function() {
      // uncomment below and update the code to test the property types
      //var instance = new NagerDateApiReference.PublicHolidayV3Dto();
      //expect(instance).to.be();
    });

  });

}));
