/* tslint:disable */
/* eslint-disable */
/**
 * Nager.Date API Reference
 * The Nager.Date API is a free public service that provides reliable information about public holidays and long weekends for countries around the world. It allows developers to query national holiday dates, check whether a specific day is a public holiday, list upcoming holidays, and explore long-weekend data.    By using the API, you agree to the <a href=\"https://date.nager.at/Legal/TermsOfService\">Terms of Service.</a>
 *
 * The version of the OpenAPI document: v3
 * Contact: hello@nager.software
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * Detailed information about a country.
 * @export
 * @interface CountryInfoDto
 */
export interface CountryInfoDto {
  /**
   * The commonly used name of the country.
   * @type {string}
   * @memberof CountryInfoDto
   */
  commonName: string;
  /**
   * The official name of the country.
   * @type {string}
   * @memberof CountryInfoDto
   */
  officialName: string;
  /**
   * ISO 3166-1 alpha-2 country code.
   * @type {string}
   * @memberof CountryInfoDto
   */
  countryCode: string;
  /**
   * Geopolitical or continental region of the country.
   * @type {string}
   * @memberof CountryInfoDto
   */
  region: string;
}

/**
 * Check if a given object implements the CountryInfoDto interface.
 */
export function instanceOfCountryInfoDto(
  value: object,
): value is CountryInfoDto {
  if (!("commonName" in value) || value["commonName"] === undefined)
    return false;
  if (!("officialName" in value) || value["officialName"] === undefined)
    return false;
  if (!("countryCode" in value) || value["countryCode"] === undefined)
    return false;
  if (!("region" in value) || value["region"] === undefined) return false;
  return true;
}

export function CountryInfoDtoFromJSON(json: any): CountryInfoDto {
  return CountryInfoDtoFromJSONTyped(json, false);
}

export function CountryInfoDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CountryInfoDto {
  if (json == null) {
    return json;
  }
  return {
    commonName: json["commonName"],
    officialName: json["officialName"],
    countryCode: json["countryCode"],
    region: json["region"],
  };
}

export function CountryInfoDtoToJSON(json: any): CountryInfoDto {
  return CountryInfoDtoToJSONTyped(json, false);
}

export function CountryInfoDtoToJSONTyped(
  value?: CountryInfoDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    commonName: value["commonName"],
    officialName: value["officialName"],
    countryCode: value["countryCode"],
    region: value["region"],
  };
}
