/* tslint:disable */
/* eslint-disable */
/**
 * Nager.Date API Reference
 * The Nager.Date API is a free public service that provides reliable information about public holidays and long weekends for countries around the world. It allows developers to query national holiday dates, check whether a specific day is a public holiday, list upcoming holidays, and explore long-weekend data.    By using the API, you agree to the <a href=\"https://date.nager.at/Legal/TermsOfService\">Terms of Service.</a>
 *
 * The version of the OpenAPI document: v3
 * Contact: hello@nager.software
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { CountryInfoDto } from "./CountryInfoDto";
import {
  CountryInfoDtoFromJSON,
  CountryInfoDtoFromJSONTyped,
  CountryInfoDtoToJSON,
  CountryInfoDtoToJSONTyped,
} from "./CountryInfoDto";

/**
 * Detailed information about a country, including neighboring countries.
 * @export
 * @interface CountryInfoWithBordersDto
 */
export interface CountryInfoWithBordersDto {
  /**
   * The commonly used name of the country.
   * @type {string}
   * @memberof CountryInfoWithBordersDto
   */
  commonName: string;
  /**
   * The official name of the country.
   * @type {string}
   * @memberof CountryInfoWithBordersDto
   */
  officialName: string;
  /**
   * ISO 3166-1 alpha-2 country code.
   * @type {string}
   * @memberof CountryInfoWithBordersDto
   */
  countryCode: string;
  /**
   * Geopolitical or continental region of the country.
   * @type {string}
   * @memberof CountryInfoWithBordersDto
   */
  region: string;
  /**
   * Neighboring countries based on geographical borders.
   * @type {Array<CountryInfoDto>}
   * @memberof CountryInfoWithBordersDto
   */
  borders?: Array<CountryInfoDto> | null;
}

/**
 * Check if a given object implements the CountryInfoWithBordersDto interface.
 */
export function instanceOfCountryInfoWithBordersDto(
  value: object,
): value is CountryInfoWithBordersDto {
  if (!("commonName" in value) || value["commonName"] === undefined)
    return false;
  if (!("officialName" in value) || value["officialName"] === undefined)
    return false;
  if (!("countryCode" in value) || value["countryCode"] === undefined)
    return false;
  if (!("region" in value) || value["region"] === undefined) return false;
  return true;
}

export function CountryInfoWithBordersDtoFromJSON(
  json: any,
): CountryInfoWithBordersDto {
  return CountryInfoWithBordersDtoFromJSONTyped(json, false);
}

export function CountryInfoWithBordersDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CountryInfoWithBordersDto {
  if (json == null) {
    return json;
  }
  return {
    commonName: json["commonName"],
    officialName: json["officialName"],
    countryCode: json["countryCode"],
    region: json["region"],
    borders:
      json["borders"] == null
        ? undefined
        : (json["borders"] as Array<any>).map(CountryInfoDtoFromJSON),
  };
}

export function CountryInfoWithBordersDtoToJSON(
  json: any,
): CountryInfoWithBordersDto {
  return CountryInfoWithBordersDtoToJSONTyped(json, false);
}

export function CountryInfoWithBordersDtoToJSONTyped(
  value?: CountryInfoWithBordersDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    commonName: value["commonName"],
    officialName: value["officialName"],
    countryCode: value["countryCode"],
    region: value["region"],
    borders:
      value["borders"] == null
        ? undefined
        : (value["borders"] as Array<any>).map(CountryInfoDtoToJSON),
  };
}
