/* tslint:disable */
/* eslint-disable */
/**
 * Nager.Date API Reference
 * The Nager.Date API is a free public service that provides reliable information about public holidays and long weekends for countries around the world. It allows developers to query national holiday dates, check whether a specific day is a public holiday, list upcoming holidays, and explore long-weekend data.    By using the API, you agree to the <a href=\"https://date.nager.at/Legal/TermsOfService\">Terms of Service.</a>
 *
 * The version of the OpenAPI document: v3
 * Contact: hello@nager.software
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * Represents a long weekend, including optional bridge days.
 * @export
 * @interface LongWeekendV3Dto
 */
export interface LongWeekendV3Dto {
  /**
   * The start date of the long weekend.
   * @type {Date}
   * @memberof LongWeekendV3Dto
   */
  startDate?: Date;
  /**
   * The end date of the long weekend.
   * @type {Date}
   * @memberof LongWeekendV3Dto
   */
  endDate?: Date;
  /**
   * Total number of days in the long weekend.
   * @type {number}
   * @memberof LongWeekendV3Dto
   */
  dayCount?: number;
  /**
   * Indicates whether a bridge day is required to achieve the long weekend.
   * @type {boolean}
   * @memberof LongWeekendV3Dto
   */
  needBridgeDay?: boolean;
  /**
   * Optional bridge days that extend the weekend.
   * @type {Array<Date>}
   * @memberof LongWeekendV3Dto
   */
  bridgeDays?: Array<Date>;
}

/**
 * Check if a given object implements the LongWeekendV3Dto interface.
 */
export function instanceOfLongWeekendV3Dto(
  value: object,
): value is LongWeekendV3Dto {
  return true;
}

export function LongWeekendV3DtoFromJSON(json: any): LongWeekendV3Dto {
  return LongWeekendV3DtoFromJSONTyped(json, false);
}

export function LongWeekendV3DtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): LongWeekendV3Dto {
  if (json == null) {
    return json;
  }
  return {
    startDate:
      json["startDate"] == null ? undefined : new Date(json["startDate"]),
    endDate: json["endDate"] == null ? undefined : new Date(json["endDate"]),
    dayCount: json["dayCount"] == null ? undefined : json["dayCount"],
    needBridgeDay:
      json["needBridgeDay"] == null ? undefined : json["needBridgeDay"],
    bridgeDays: json["bridgeDays"] == null ? undefined : json["bridgeDays"],
  };
}

export function LongWeekendV3DtoToJSON(json: any): LongWeekendV3Dto {
  return LongWeekendV3DtoToJSONTyped(json, false);
}

export function LongWeekendV3DtoToJSONTyped(
  value?: LongWeekendV3Dto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    startDate:
      value["startDate"] == null
        ? value["startDate"]
        : value["startDate"].toISOString().substring(0, 10),
    endDate:
      value["endDate"] == null
        ? value["endDate"]
        : value["endDate"].toISOString().substring(0, 10),
    dayCount: value["dayCount"],
    needBridgeDay: value["needBridgeDay"],
    bridgeDays: value["bridgeDays"],
  };
}
