/* tslint:disable */
/* eslint-disable */
/**
 * Nager.Date API Reference
 * The Nager.Date API is a free public service that provides reliable information about public holidays and long weekends for countries around the world. It allows developers to query national holiday dates, check whether a specific day is a public holiday, list upcoming holidays, and explore long-weekend data.    By using the API, you agree to the <a href=\"https://date.nager.at/Legal/TermsOfService\">Terms of Service.</a>
 *
 * The version of the OpenAPI document: v3
 * Contact: hello@nager.software
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { HolidayTypes } from "./HolidayTypes";
import {
  HolidayTypesFromJSON,
  HolidayTypesFromJSONTyped,
  HolidayTypesToJSON,
  HolidayTypesToJSONTyped,
} from "./HolidayTypes";

/**
 * Represents a public holiday.
 * @export
 * @interface PublicHolidayV3Dto
 */
export interface PublicHolidayV3Dto {
  /**
   * The date of the holiday.
   * @type {Date}
   * @memberof PublicHolidayV3Dto
   */
  date: Date;
  /**
   * Local name of the holiday.
   * @type {string}
   * @memberof PublicHolidayV3Dto
   */
  localName: string;
  /**
   * English name of the holiday.
   * @type {string}
   * @memberof PublicHolidayV3Dto
   */
  name: string;
  /**
   * ISO 3166-1 alpha-2 country code.
   * @type {string}
   * @memberof PublicHolidayV3Dto
   */
  countryCode: string;
  /**
   * Indicates if this holiday occurs on the same date every year.
   * @type {boolean}
   * @memberof PublicHolidayV3Dto
   */
  fixed?: boolean;
  /**
   * Indicates if this holiday applies to the entire country.
   * @type {boolean}
   * @memberof PublicHolidayV3Dto
   */
  global?: boolean;
  /**
   * ISO-3166-2 codes of the subdivisions where this holiday applies
   * @type {Array<string>}
   * @memberof PublicHolidayV3Dto
   */
  counties?: Array<string> | null;
  /**
   * The year the holiday was first observed.
   * @type {number}
   * @memberof PublicHolidayV3Dto
   */
  launchYear?: number | null;
  /**
   * List of holiday types this holiday is classified under.
   * @type {Array<HolidayTypes>}
   * @memberof PublicHolidayV3Dto
   */
  types: Array<HolidayTypes>;
}

/**
 * Check if a given object implements the PublicHolidayV3Dto interface.
 */
export function instanceOfPublicHolidayV3Dto(
  value: object,
): value is PublicHolidayV3Dto {
  if (!("date" in value) || value["date"] === undefined) return false;
  if (!("localName" in value) || value["localName"] === undefined) return false;
  if (!("name" in value) || value["name"] === undefined) return false;
  if (!("countryCode" in value) || value["countryCode"] === undefined)
    return false;
  if (!("types" in value) || value["types"] === undefined) return false;
  return true;
}

export function PublicHolidayV3DtoFromJSON(json: any): PublicHolidayV3Dto {
  return PublicHolidayV3DtoFromJSONTyped(json, false);
}

export function PublicHolidayV3DtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PublicHolidayV3Dto {
  if (json == null) {
    return json;
  }
  return {
    date: new Date(json["date"]),
    localName: json["localName"],
    name: json["name"],
    countryCode: json["countryCode"],
    fixed: json["fixed"] == null ? undefined : json["fixed"],
    global: json["global"] == null ? undefined : json["global"],
    counties: json["counties"] == null ? undefined : json["counties"],
    launchYear: json["launchYear"] == null ? undefined : json["launchYear"],
    types: (json["types"] as Array<any>).map(HolidayTypesFromJSON),
  };
}

export function PublicHolidayV3DtoToJSON(json: any): PublicHolidayV3Dto {
  return PublicHolidayV3DtoToJSONTyped(json, false);
}

export function PublicHolidayV3DtoToJSONTyped(
  value?: PublicHolidayV3Dto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    date: value["date"].toISOString().substring(0, 10),
    localName: value["localName"],
    name: value["name"],
    countryCode: value["countryCode"],
    fixed: value["fixed"],
    global: value["global"],
    counties: value["counties"],
    launchYear: value["launchYear"],
    types: (value["types"] as Array<any>).map(HolidayTypesToJSON),
  };
}
